# Generated by Django 4.2 on 2025-07-09 15:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='visit_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shorturl',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='shorturl',
            name='short_url',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='shorturl',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
