# Generated by Django 4.2 on 2025-07-10 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_shorturl_visit_count_alter_shorturl_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='visited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
